export const TOWN_AREA = [
    { label: "Abbots Langley", value: "abbots-langley" },
    { label: "Aberaeron", value: "aberaeron" },
    { label: "Aberdare", value: "aberdare" },
    { label: "Aberdeen", value: "aberdeen" },
    { label: "Aberdovey", value: "aberdovey" },
    { label: "Aberfeldy", value: "aberfeldy" },
    { label: "Abergavenny", value: "abergavenny" },
    { label: "Abergele", value: "abergele" },
    { label: "Aberlour", value: "aberlour" },
    { label: "Abertillery", value: "abertillery" },
    { label: "Abingdon", value: "abingdon" },
    { label: "Aboyne", value: "aboyne" },
    { label: "Accrington", value: "accrington" },
    { label: "Acharacle", value: "acharacle" },
    { label: "Achnasheen", value: "achnasheen" },
    { label: "Acton", value: "acton" },
    { label: "Addington", value: "addington" },
    { label: "Addlestone", value: "addlestone" },
    { label: "Airdrie", value: "airdrie" },
    { label: "Aldeburgh", value: "aldeburgh" },
    { label: "Alderley Edge", value: "alderley-edge" },
    { label: "Aldershot", value: "aldershot" },
    { label: "Aldgate", value: "aldgate" },
    { label: "Aldwych", value: "aldwych" },
    { label: "Alford", value: "alford" },
    { label: "Alfreton", value: "alfreton" },
    { label: "Alloa", value: "alloa" },
    { label: "Alness", value: "alness" },
    { label: "Alnwick", value: "alnwick" },
    { label: "Alresford", value: "alresford" },
    { label: "Alston", value: "alston" },
    { label: "Alton", value: "alton" },
    { label: "Altrincham", value: "altrincham" },
    { label: "Alva", value: "alva" },
    { label: "Ambleside", value: "ambleside" },
    { label: "Amersham", value: "amersham" },
    { label: "Amlwch", value: "amlwch" },
    { label: "Ammanford", value: "ammanford" },
    { label: "anchester", value: "anchester" },
    { label: "Andover", value: "andover" },
    { label: "Annan", value: "annan" },
    { label: "Anstruther", value: "anstruther" },
    { label: "Antrim", value: "antrim" },
    { label: "Apartments all over London", value: "apartments-all-over-london" },
    { label: "Appin", value: "appin" },
    { label: "Appleby-in-Westmorland", value: "appleby-in-westmorland" },
    { label: "Arbroath", value: "arbroath" },
    { label: "Archway", value: "archway" },
    { label: "Ardgay", value: "ardgay" },
    { label: "Ardrossan", value: "ardrossan" },
    { label: "Arisaig", value: "arisaig" },
    { label: "Arlesey", value: "arlesey" },
    { label: "Armagh", value: "armagh" },
    { label: "arnsley", value: "arnsley" },
    { label: "Arrochar", value: "arrochar" },
    { label: "Arthog", value: "arthog" },
    { label: "Artillery Liberty", value: "artillery-liberty" },
    { label: "Arundel", value: "arundel" },
    { label: "Ascot", value: "ascot" },
    { label: "Ashbourne", value: "ashbourne" },
    { label: "Ashburton", value: "ashburton" },
    { label: "Ashby-de-la-Zouch", value: "ashby-de-la-zouch" },
    { label: "Ashford", value: "ashford" },
    { label: "Ashington", value: "ashington" },
    { label: "Ashtead", value: "ashtead" },
    { label: "Ashton-Under-Lyne", value: "ashton-under-lyne" },
    { label: "Askam-in-Furness", value: "askam-in-furness" },
    { label: "Atherstone", value: "atherstone" },
    { label: "Attleborough", value: "attleborough" },
    { label: "Auchterarder", value: "auchterarder" },
    { label: "Augher", value: "augher" },
    { label: "Aughnacloy", value: "aughnacloy" },
    { label: "Aviemore", value: "aviemore" },
    { label: "Avoch", value: "avoch" },
    { label: "Axbridge", value: "axbridge" },
    { label: "Axminster", value: "axminster" },
    { label: "Aylesbury", value: "aylesbury" },
    { label: "Aylesford", value: "aylesford" },
    { label: "Ayr", value: "ayr" },
    { label: "Bacup", value: "bacup" },
    { label: "Badminton", value: "badminton" },
    { label: "Bagillt", value: "bagillt" },
    { label: "Bagshot", value: "bagshot" },
    { label: "Bakewell", value: "bakewell" },
    { label: "Bala", value: "bala" },
    { label: "Baldock", value: "baldock" },
    { label: "Balerno", value: "balerno" },
    { label: "Balham", value: "balham" },
    { label: "Ballachulish", value: "ballachulish" },
    { label: "Ballater", value: "ballater" },
    { label: "Ballindalloch", value: "ballindalloch" },
    { label: "Ballycastle", value: "ballycastle" },
    { label: "Ballyclare", value: "ballyclare" },
    { label: "Ballymena", value: "ballymena" },
    { label: "Ballymoney", value: "ballymoney" },
    { label: "Ballynahinch", value: "ballynahinch" },
    { label: "Bamburgh", value: "bamburgh" },
    { label: "Bampton", value: "bampton" },
    { label: "Banbridge", value: "banbridge" },
    { label: "Banbury", value: "banbury" },
    { label: "Banchory", value: "banchory" },
    { label: "Banff", value: "banff" },
    { label: "Bangor", value: "bangor" },
    { label: "Bank", value: "bank" },
    { label: "Bankside", value: "bankside" },
    { label: "Banstead", value: "banstead" },
    { label: "Banwell", value: "banwell" },
    { label: "Barbican", value: "barbican" },
    { label: "Bargoed", value: "bargoed" },
    { label: "Barking", value: "barking" },
    { label: "Barkingside", value: "barkingside" },
    { label: "Barmouth", value: "barmouth" },
    { label: "Barnard Castle", value: "barnard-castle" },
    { label: "Barnes", value: "barnes" },
    { label: "Barnet", value: "barnet" },
    { label: "Barnetby", value: "barnetby" },
    { label: "Barnoldswick", value: "barnoldswick" },
    { label: "Barnstaple", value: "barnstaple" },
    { label: "Barrow upon Humber", value: "barrow-upon-humber" },
    { label: "Barrow-in-Furness", value: "barrow-in-furness" },
    { label: "Barry", value: "barry" },
    { label: "Barton-upon-Humber", value: "barton-upon-humber" },
    { label: "Basildon", value: "basildon" },
    { label: "Basingstoke", value: "basingstoke" },
    { label: "Bath", value: "bath" },
    { label: "Bathgate", value: "bathgate" },
    { label: "Batley", value: "batley" },
    { label: "Battersea", value: "battersea" },
    { label: "Battle", value: "battle" },
    { label: "Bayswater", value: "bayswater" },
    { label: "Beaconsfield", value: "beaconsfield" },
    { label: "Beaminster", value: "beaminster" },
    { label: "Beauly", value: "beauly" },
    { label: "Beaumaris", value: "beaumaris" },
    { label: "Beaworthy", value: "beaworthy" },
    { label: "Beccles", value: "beccles" },
    { label: "Beckenham", value: "beckenham" },
    { label: "Beckermet", value: "beckermet" },
    { label: "Beckton", value: "beckton" },
    { label: "Becontree", value: "becontree" },
    { label: "Bedale", value: "bedale" },
    { label: "Bedford", value: "bedford" },
    { label: "Bedlington", value: "bedlington" },
    { label: "Bedworth", value: "bedworth" },
    { label: "Beith", value: "beith" },
    { label: "Belfast", value: "belfast" },
    { label: "Belford", value: "belford" },
    { label: "Belgravia", value: "belgravia" },
    { label: "Bellshill", value: "bellshill" },
    { label: "Belper", value: "belper" },
    { label: "Belsize Park", value: "belsize-park" },
    { label: "Belvedere", value: "belvedere" },
    { label: "Bembridge", value: "bembridge" },
    { label: "Benfleet", value: "benfleet" },
    { label: "Berkeley", value: "berkeley" },
    { label: "Berkhamsted", value: "berkhamsted" },
    { label: "Bermondsey", value: "bermondsey" },
    { label: "Berriedale", value: "berriedale" },
    { label: "Berwick-Upon-Tweed", value: "berwick-upon-tweed" },
    { label: "Betchworth", value: "betchworth" },
    { label: "Bethnal Green", value: "bethnal-green" },
    { label: "Betws-y-Coed", value: "betws-y-coed" },
    { label: "Beverley", value: "beverley" },
    { label: "Bewdley", value: "bewdley" },
    { label: "Bexhill-on-Sea", value: "bexhill-on-sea" },
    { label: "Bexley", value: "bexley" },
    { label: "Bexleyheath", value: "bexleyheath" },
    { label: "Bicester", value: "bicester" },
    { label: "Bideford", value: "bideford" },
    { label: "Biggar", value: "biggar" },
    { label: "Biggin Hill", value: "biggin-hill" },
    { label: "Biggleswade", value: "biggleswade" },
    { label: "Billericay", value: "billericay" },
    { label: "Billingham", value: "billingham" },
    { label: "Billingshurst", value: "billingshurst" },
    { label: "Bilston", value: "bilston" },
    { label: "Bingley", value: "bingley" },
    { label: "Birchington", value: "birchington" },
    { label: "Birkenhead", value: "birkenhead" },
    { label: "Birmingham", value: "birmingham" },
    { label: "Bishop Auckland", value: "bishop-auckland" },
    { label: "Bishops Castle", value: "bishops-castle" },
    { label: "Bishop's Stortford", value: "bishops-stortford" },
    { label: "Bishopsgate", value: "bishopsgate" },
    { label: "Bishopton", value: "bishopton" },
    { label: "Blackburn", value: "blackburn" },
    { label: "Blackfriars", value: "blackfriars" },
    { label: "Blackheath", value: "blackheath" },
    { label: "Blackpool", value: "blackpool" },
    { label: "Blackwood", value: "blackwood" },
    { label: "Blaenau Ffestiniog", value: "blaenau-ffestiniog" },
    { label: "Blairgowrie", value: "blairgowrie" },
    { label: "Blakeney", value: "blakeney" },
    { label: "Blandford Forum", value: "blandford-forum" },
    { label: "Blaydon-on-Tyne", value: "blaydon-on-tyne" },
    { label: "Bloomsbury", value: "bloomsbury" },
    { label: "Blyth", value: "blyth" },
    { label: "Boat of Garten", value: "boat-of-garten" },
    { label: "Bodmin", value: "bodmin" },
    { label: "Bodorgan", value: "bodorgan" },
    { label: "Bognor Regis", value: "bognor-regis" },
    { label: "Boldon Colliery", value: "boldon-colliery" },
    { label: "Bolton", value: "bolton" },
    { label: "Boncath", value: "boncath" },
    { label: "Bo'ness", value: "boness" },
    { label: "Bonnybridge", value: "bonnybridge" },
    { label: "Bonnyrigg", value: "bonnyrigg" },
    { label: "Bootle", value: "bootle" },
    { label: "Bordon", value: "bordon" },
    { label: "Borehamwood", value: "borehamwood" },
    { label: "Borough", value: "borough" },
    { label: "Borth", value: "borth" },
    { label: "Boscastle", value: "boscastle" },
    { label: "Boston", value: "boston" },
    { label: "Bourne", value: "bourne" },
    { label: "Bourne End", value: "bourne-end" },
    { label: "Bournemouth", value: "bournemouth" },
    { label: "Bow", value: "bow" },
    { label: "Bow Street", value: "bow-street" },
    { label: "Brackley", value: "brackley" },
    { label: "Bracknell", value: "bracknell" },
    { label: "Bradford", value: "bradford" },
    { label: "Bradford on Avon", value: "bradford-on-avon" },
    { label: "Braintree", value: "braintree" },
    { label: "Brampton", value: "brampton" },
    { label: "Brandon", value: "brandon" },
    { label: "Braunton", value: "braunton" },
    { label: "Brechin", value: "brechin" },
    { label: "Brecon", value: "brecon" },
    { label: "Brent Cross", value: "brent-cross" },
    { label: "Brentford", value: "brentford" },
    { label: "Brentwood", value: "brentwood" },
    { label: "Bridge of Orchy", value: "bridge-of-orchy" },
    { label: "Bridge of Weir", value: "bridge-of-weir" },
    { label: "Bridgend", value: "bridgend" },
    { label: "Bridgnorth", value: "bridgnorth" },
    { label: "Bridgwater", value: "bridgwater" },
    { label: "Bridlington", value: "bridlington" },
    { label: "Bridport", value: "bridport" },
    { label: "Brierley Hill", value: "brierley-hill" },
    { label: "Brigg", value: "brigg" },
    { label: "Brighouse", value: "brighouse" },
    { label: "Brighton", value: "brighton" },
    { label: "Bristol", value: "bristol" },
    { label: "Brixham", value: "brixham" },
    { label: "Brixton", value: "brixton" },
    { label: "Broad St", value: "broad-st" },
    { label: "Broadgate", value: "broadgate" },
    { label: "Broadstairs", value: "broadstairs" },
    { label: "Broadstone", value: "broadstone" },
    { label: "Broadway", value: "broadway" },
    { label: "Brockenhurst", value: "brockenhurst" },
    { label: "Bromley", value: "bromley" },
    { label: "Bromley by Bow", value: "bromley-by-bow" },
    { label: "Bromley St Leonard", value: "bromley-st-leonard" },
    { label: "Bromsgrove", value: "bromsgrove" },
    { label: "Bromyard", value: "bromyard" },
    { label: "Brondesbury", value: "brondesbury" },
    { label: "Brook Green", value: "brook-green" },
    { label: "Brora", value: "brora" },
    { label: "Broseley", value: "broseley" },
    { label: "Brough", value: "brough" },
    { label: "Broughton-in-Furness", value: "broughton-in-furness" },
    { label: "Broxbourne", value: "broxbourne" },
    { label: "Broxburn", value: "broxburn" },
    { label: "Bruton", value: "bruton" },
    { label: "Brynteg", value: "brynteg" },
    { label: "Buckfastleigh", value: "buckfastleigh" },
    { label: "Buckhurst Hill", value: "buckhurst-hill" },
    { label: "Buckie", value: "buckie" },
    { label: "Buckingham", value: "buckingham" },
    { label: "Buckley", value: "buckley" },
    { label: "Bucknell", value: "bucknell" },
    { label: "Bude", value: "bude" },
    { label: "Budleigh Salterton", value: "budleigh-salterton" },
    { label: "Builth Wells", value: "builth-wells" },
    { label: "Bungay", value: "bungay" },
    { label: "Buntingford", value: "buntingford" },
    { label: "Bures", value: "bures" },
    { label: "Burford", value: "burford" },
    { label: "Burgess Hill", value: "burgess-hill" },
    { label: "Burnham-on-Crouch", value: "burnham-on-crouch" },
    { label: "Burnham-on-Sea", value: "burnham-on-sea" },
    { label: "Burnley", value: "burnley" },
    { label: "Burntisland", value: "burntisland" },
    { label: "Burntwood", value: "burntwood" },
    { label: "Burry Port", value: "burry-port" },
    { label: "Burton upon Trent", value: "burton-upon-trent" },
    { label: "Bury", value: "bury" },
    { label: "Bury St Edmunds", value: "bury-st-edmunds" },
    { label: "Bushey", value: "bushey" },
    { label: "Bushmills", value: "bushmills" },
    { label: "Buxton", value: "buxton" },
    { label: "Caernarfon", value: "caernarfon" },
    { label: "Caerphilly", value: "caerphilly" },
    { label: "Caersws", value: "caersws" },
    { label: "Cairndow", value: "cairndow" },
    { label: "Caldicot", value: "caldicot" },
    { label: "Caledon", value: "caledon" },
    { label: "Callander", value: "callander" },
    { label: "Callington", value: "callington" },
    { label: "Calne", value: "calne" },
    { label: "Calstock", value: "calstock" },
    { label: "Camberley", value: "camberley" },
    { label: "Camberwell", value: "camberwell" },
    { label: "Camborne", value: "camborne" },
    { label: "Cambridge", value: "cambridge" },
    { label: "Camden", value: "camden" },
    { label: "Camelford", value: "camelford" },
    { label: "Campbeltown", value: "campbeltown" },
    { label: "Canary Wharf", value: "canary-wharf" },
    { label: "Canning Town", value: "canning-town" },
    { label: "Cannock", value: "cannock" },
    { label: "Canonbie", value: "canonbie" },
    { label: "Canonbury", value: "canonbury" },
    { label: "Canterbury", value: "canterbury" },
    { label: "Canvey Island", value: "canvey-island" },
    { label: "Cardiff", value: "cardiff" },
    { label: "Cardigan", value: "cardigan" },
    { label: "Carlisle", value: "carlisle" },
    { label: "Carluke", value: "carluke" },
    { label: "Carmarthen", value: "carmarthen" },
    { label: "Carnforth", value: "carnforth" },
    { label: "Carnoustie", value: "carnoustie" },
    { label: "Carrbridge", value: "carrbridge" },
    { label: "Carrickfergus", value: "carrickfergus" },
    { label: "Carshalton", value: "carshalton" },
    { label: "Carterton", value: "carterton" },
    { label: "Castle Cary", value: "castle-cary" },
    { label: "Castle Douglas", value: "castle-douglas" },
    { label: "Castlederg", value: "castlederg" },
    { label: "Castleford", value: "castleford" },
    { label: "Castlewellan", value: "castlewellan" },
    { label: "Caterham", value: "caterham" },
    { label: "Catford", value: "catford" },
    { label: "Catterick Garrison", value: "catterick-garrison" },
    { label: "Cemaes Bay", value: "cemaes-bay" },
    { label: "Chadwell Heath", value: "chadwell-heath" },
    { label: "Chalfont St Giles", value: "chalfont-st-giles" },
    { label: "Chard", value: "chard" },
    { label: "Charing Cross", value: "charing-cross" },
    { label: "Charlton", value: "charlton" },
    { label: "Chatham", value: "chatham" },
    { label: "Chathill", value: "chathill" },
    { label: "Chatteris", value: "chatteris" },
    { label: "Cheadle", value: "cheadle" },
    { label: "Cheddar", value: "cheddar" },
    { label: "Chelmsford", value: "chelmsford" },
    { label: "Chelsea", value: "chelsea" },
    { label: "Cheltenham", value: "cheltenham" },
    { label: "Chepstow", value: "chepstow" },
    { label: "Chertsey", value: "chertsey" },
    { label: "Chesham", value: "chesham" },
    { label: "Chessington", value: "chessington" },
    { label: "Chester", value: "chester" },
    { label: "Chester le Street", value: "chester-le-street" },
    { label: "Chesterfield", value: "chesterfield" },
    { label: "Chichester", value: "chichester" },
    { label: "Chigwell", value: "chigwell" },
    { label: "Chingford", value: "chingford" },
    { label: "Chinnor", value: "chinnor" },
    { label: "Chippenham", value: "chippenham" },
    { label: "Chipping Campden", value: "chipping-campden" },
    { label: "Chipping Norton", value: "chipping-norton" },
    { label: "Chislehurst", value: "chislehurst" },
    { label: "Chiswick", value: "chiswick" },
    { label: "Choppington", value: "choppington" },
    { label: "Chorley", value: "chorley" },
    { label: "Christchurch", value: "christchurch" },
    { label: "Chulmleigh", value: "chulmleigh" },
    { label: "Church Stretton", value: "church-stretton" },
    { label: "Cinderford", value: "cinderford" },
    { label: "Cirencester", value: "cirencester" },
    { label: "City", value: "city" },
    { label: "Clackmannan", value: "clackmannan" },
    { label: "Clacton-on-Sea", value: "clacton-on-sea" },
    { label: "Clapham", value: "clapham" },
    { label: "Clapton", value: "clapton" },
    { label: "Clarbeston Road", value: "clarbeston-road" },
    { label: "Clayhall", value: "clayhall" },
    { label: "Cleator", value: "cleator" },
    { label: "Cleator Moor", value: "cleator-moor" },
    { label: "Cleckheaton", value: "cleckheaton" },
    { label: "Cleethorpes", value: "cleethorpes" },
    { label: "Clerkenwell", value: "clerkenwell" },
    { label: "Clevedon", value: "clevedon" },
    { label: "Clitheroe", value: "clitheroe" },
    { label: "Clogher", value: "clogher" },
    { label: "Clydebank", value: "clydebank" },
    { label: "Clynderwen", value: "clynderwen" },
    { label: "Coalville", value: "coalville" },
    { label: "Coatbridge", value: "coatbridge" },
    { label: "Cobham", value: "cobham" },
    { label: "Cockburnspath", value: "cockburnspath" },
    { label: "Cockermouth", value: "cockermouth" },
    { label: "Colchester", value: "colchester" },
    { label: "Coldstream", value: "coldstream" },
    { label: "Coleford", value: "coleford" },
    { label: "Coleraine", value: "coleraine" },
    { label: "Colintraive", value: "colintraive" },
    { label: "Collier Row", value: "collier-row" },
    { label: "Colne", value: "colne" },
    { label: "Colwyn Bay", value: "colwyn-bay" },
    { label: "Colyton", value: "colyton" },
    { label: "Congleton", value: "congleton" },
    { label: "Coniston", value: "coniston" },
    { label: "Consett", value: "consett" },
    { label: "Conwy", value: "conwy" },
    { label: "Cookstown", value: "cookstown" },
    { label: "Corbets Tey", value: "corbets-tey" },
    { label: "Corbridge", value: "corbridge" },
    { label: "Corby", value: "corby" },
    { label: "Cornhill-on-Tweed", value: "cornhill-on-tweed" },
    { label: "Corrour", value: "corrour" },
    { label: "Corsham", value: "corsham" },
    { label: "Corwen", value: "corwen" },
    { label: "Cottingham", value: "cottingham" },
    { label: "Coulsdon", value: "coulsdon" },
    { label: "Countywide", value: "countywide" },
    { label: "Covent Garden", value: "covent-garden" },
    { label: "Coventry", value: "coventry" },
    { label: "Cowbridge", value: "cowbridge" },
    { label: "Cowdenbeath", value: "cowdenbeath" },
    { label: "Cowes", value: "cowes" },
    { label: "Cradley Heath", value: "cradley-heath" },
    { label: "Craigavon", value: "craigavon" },
    { label: "Cramlington", value: "cramlington" },
    { label: "Cranbrook", value: "cranbrook" },
    { label: "Cranham", value: "cranham" },
    { label: "Cranleigh", value: "cranleigh" },
    { label: "Craven Arms", value: "craven-arms" },
    { label: "Crawley", value: "crawley" },
    { label: "Crediton", value: "crediton" },
    { label: "Crewe", value: "crewe" },
    { label: "Crewkerne", value: "crewkerne" },
    { label: "Crianlarich", value: "crianlarich" },
    { label: "Criccieth", value: "criccieth" },
    { label: "Crickhowell", value: "crickhowell" },
    { label: "Cricklewood", value: "cricklewood" },
    { label: "Crieff", value: "crieff" },
    { label: "Cromarty", value: "cromarty" },
    { label: "Cromer", value: "cromer" },
    { label: "Crook", value: "crook" },
    { label: "Crouch End", value: "crouch-end" },
    { label: "Crowborough", value: "crowborough" },
    { label: "Crowthorne", value: "crowthorne" },
    { label: "Croydon", value: "croydon" },
    { label: "Crumlin", value: "crumlin" },
    { label: "Crymych", value: "crymych" },
    { label: "Crystal Palace", value: "crystal-palace" },
    { label: "Cullompton", value: "cullompton" },
    { label: "Cumnock", value: "cumnock" },
    { label: "Cupar", value: "cupar" },
    { label: "Currie", value: "currie" },
    { label: "Custom House", value: "custom-house" },
    { label: "Cwmbran", value: "cwmbran" },
    { label: "Dagenham", value: "dagenham" },
    { label: "Dagenham East", value: "dagenham-east" },
    { label: "Dagenham Heathway", value: "dagenham-heathway" },
    { label: "Dagenham Village", value: "dagenham-village" },
    { label: "Dalbeattie", value: "dalbeattie" },
    { label: "Dalkeith", value: "dalkeith" },
    { label: "Dalmally", value: "dalmally" },
    { label: "Dalry", value: "dalry" },
    { label: "Dalston", value: "dalston" },
    { label: "Dalton-in-Furness", value: "dalton-in-furness" },
    { label: "Dalwhinnie", value: "dalwhinnie" },
    { label: "Darlington", value: "darlington" },
    { label: "Dartford", value: "dartford" },
    { label: "Dartmouth", value: "dartmouth" },
    { label: "Darvel", value: "darvel" },
    { label: "Darwen", value: "darwen" },
    { label: "Daventry", value: "daventry" },
    { label: "Dawlish", value: "dawlish" },
    { label: "Deal", value: "deal" },
    { label: "Deeside", value: "deeside" },
    { label: "Delabole", value: "delabole" },
    { label: "Denbigh", value: "denbigh" },
    { label: "Denny", value: "denny" },
    { label: "Deptford", value: "deptford" },
    { label: "Derby", value: "derby" },
    { label: "Dereham", value: "dereham" },
    { label: "Devizes", value: "devizes" },
    { label: "Dewsbury", value: "dewsbury" },
    { label: "Didcot", value: "didcot" },
    { label: "Dinas Powys", value: "dinas-powys" },
    { label: "Dingwall", value: "dingwall" },
    { label: "Diss", value: "diss" },
    { label: "Docklands", value: "docklands" },
    { label: "Dolgellau", value: "dolgellau" },
    { label: "Dollar", value: "dollar" },
    { label: "Dolwyddelan", value: "dolwyddelan" },
    { label: "Donaghadee", value: "donaghadee" },
    { label: "Doncaster", value: "doncaster" },
    { label: "Dorchester", value: "dorchester" },
    { label: "Dorking", value: "dorking" },
    { label: "Dornoch", value: "dornoch" },
    { label: "Doune", value: "doune" },
    { label: "Dover", value: "dover" },
    { label: "Downham Market", value: "downham-market" },
    { label: "Downpatrick", value: "downpatrick" },
    { label: "Driffield", value: "driffield" },
    { label: "Droitwich", value: "droitwich" },
    { label: "Dromore", value: "dromore" },
    { label: "Dronfield", value: "dronfield" },
    { label: "Drybrook", value: "drybrook" },
    { label: "Dudley", value: "dudley" },
    { label: "Dukinfield", value: "dukinfield" },
    { label: "Dulas", value: "dulas" },
    { label: "Dulverton", value: "dulverton" },
    { label: "Dulwich", value: "dulwich" },
    { label: "Dumbarton", value: "dumbarton" },
    { label: "Dumfries", value: "dumfries" },
    { label: "Dunbar", value: "dunbar" },
    { label: "Dunbeath", value: "dunbeath" },
    { label: "Dunblane", value: "dunblane" },
    { label: "Dundee", value: "dundee" },
    { label: "Dunfermline", value: "dunfermline" },
    { label: "Dungannon", value: "dungannon" },
    { label: "Dunkeld", value: "dunkeld" },
    { label: "Dunmow", value: "dunmow" },
    { label: "Dunoon", value: "dunoon" },
    { label: "Duns", value: "duns" },
    { label: "Dunstable", value: "dunstable" },
    { label: "Durham", value: "durham" },
    { label: "Dursley", value: "dursley" },
    { label: "Dyffryn Ardudwy", value: "dyffryn-ardudwy" },
    { label: "Dymock", value: "dymock" },
    { label: "Ealing", value: "ealing" },
    { label: "Earls Court", value: "earls-court" },
    { label: "Earlston", value: "earlston" },
    { label: "East Boldon", value: "east-boldon" },
    { label: "East Cowes", value: "east-cowes" },
    { label: "East Dulwich", value: "east-dulwich" },
    { label: "East Grinstead", value: "east-grinstead" },
    { label: "East Ham", value: "east-ham" },
    { label: "East Linton", value: "east-linton" },
    { label: "East Molesey", value: "east-molesey" },
    { label: "East Sheen", value: "east-sheen" },
    { label: "Eastbourne", value: "eastbourne" },
    { label: "Eastcote", value: "eastcote" },
    { label: "Eastleigh", value: "eastleigh" },
    { label: "Ebbw Vale", value: "ebbw-vale" },
    { label: "Edenbridge", value: "edenbridge" },
    { label: "Edgware", value: "edgware" },
    { label: "Edinburgh", value: "edinburgh" },
    { label: "Edmonton", value: "edmonton" },
    { label: "Egham", value: "egham" },
    { label: "Egremont", value: "egremont" },
    { label: "Elgin", value: "elgin" },
    { label: "Elland", value: "elland" },
    { label: "Ellesmere", value: "ellesmere" },
    { label: "Ellesmere Port", value: "ellesmere-port" },
    { label: "Ellon", value: "ellon" },
    { label: "Elm Park", value: "elm-park" },
    { label: "Eltham", value: "eltham" },
    { label: "Ely", value: "ely" },
    { label: "Embankment", value: "embankment" },
    { label: "Emerson Park", value: "emerson-park" },
    { label: "Emsworth", value: "emsworth" },
    { label: "Enfield", value: "enfield" },
    { label: "Enniskillen", value: "enniskillen" },
    { label: "Epping", value: "epping" },
    { label: "Epsom", value: "epsom" },
    { label: "Erith", value: "erith" },
    { label: "Erskine", value: "erskine" },
    { label: "Esher", value: "esher" },
    { label: "Etchingham", value: "etchingham" },
    { label: "Euston", value: "euston" },
    { label: "Evesham", value: "evesham" },
    { label: "Exchange Square", value: "exchange-square" },
    { label: "Exeter", value: "exeter" },
    { label: "Exmouth", value: "exmouth" },
    { label: "Eye", value: "eye" },
    { label: "Eyemouth", value: "eyemouth" },
    { label: "Fairbourne", value: "fairbourne" },
    { label: "Fairford", value: "fairford" },
    { label: "Fairlop", value: "fairlop" },
    { label: "Fakenham", value: "fakenham" },
    { label: "Falkirk", value: "falkirk" },
    { label: "Falmouth", value: "falmouth" },
    { label: "Fareham", value: "fareham" },
    { label: "Faringdon", value: "faringdon" },
    { label: "Farnborough", value: "farnborough" },
    { label: "Farnham", value: "farnham" },
    { label: "Farringdon", value: "farringdon" },
    { label: "Faversham", value: "faversham" },
    { label: "Felixstowe", value: "felixstowe" },
    { label: "Feltham", value: "feltham" },
    { label: "Ferndale", value: "ferndale" },
    { label: "Ferndown", value: "ferndown" },
    { label: "Ferryhill", value: "ferryhill" },
    { label: "Ferryside", value: "ferryside" },
    { label: "Filey", value: "filey" },
    { label: "Finchley", value: "finchley" },
    { label: "Finsbury Park", value: "finsbury-park" },
    { label: "Fishguard", value: "fishguard" },
    { label: "Fitzrovia", value: "fitzrovia" },
    { label: "Fivemiletown", value: "fivemiletown" },
    { label: "Fleet", value: "fleet" },
    { label: "Fleet Street", value: "fleet-street" },
    { label: "Fleetwood", value: "fleetwood" },
    { label: "Flint", value: "flint" },
    { label: "Fochabers", value: "fochabers" },
    { label: "Folkestone", value: "folkestone" },
    { label: "Fordingbridge", value: "fordingbridge" },
    { label: "Forest Gate", value: "forest-gate" },
    { label: "Forest Hill", value: "forest-hill" },
    { label: "Forest Row", value: "forest-row" },
    { label: "Forfar", value: "forfar" },
    { label: "Forres", value: "forres" },
    { label: "Forsinard", value: "forsinard" },
    { label: "Fort Augustus", value: "fort-augustus" },
    { label: "Fort William", value: "fort-william" },
    { label: "Fortrose", value: "fortrose" },
    { label: "Fowey", value: "fowey" },
    { label: "Fraserburgh", value: "fraserburgh" },
    { label: "Freshwater", value: "freshwater" },
    { label: "Frinton-on-Sea", value: "frinton-on-sea" },
    { label: "Frizington", value: "frizington" },
    { label: "Frodsham", value: "frodsham" },
    { label: "Frome", value: "frome" },
    { label: "Fulham", value: "fulham" },
    { label: "Fullwell Cross", value: "fullwell-cross" },
    { label: "Gaerwen", value: "gaerwen" },
    { label: "Gainsborough", value: "gainsborough" },
    { label: "Gairloch", value: "gairloch" },
    { label: "Galashiels", value: "galashiels" },
    { label: "Galston", value: "galston" },
    { label: "Gants Hill Cross", value: "gants-hill-cross" },
    { label: "Garndolbenmaen", value: "garndolbenmaen" },
    { label: "Garve", value: "garve" },
    { label: "Gateshead", value: "gateshead" },
    { label: "Gatwick", value: "gatwick" },
    { label: "Gerrards Cross", value: "gerrards-cross" },
    { label: "Gidea Park", value: "gidea-park" },
    { label: "Gillingham", value: "gillingham" },
    { label: "Girvan", value: "girvan" },
    { label: "Glasgow", value: "glasgow" },
    { label: "Glastonbury", value: "glastonbury" },
    { label: "Glenfinnan", value: "glenfinnan" },
    { label: "Glenrothes", value: "glenrothes" },
    { label: "Glogue", value: "glogue" },
    { label: "Glossop", value: "glossop" },
    { label: "Gloucester", value: "gloucester" },
    { label: "Godalming", value: "godalming" },
    { label: "Godstone", value: "godstone" },
    { label: "Golders Green", value: "golders-green" },
    { label: "Golspie", value: "golspie" },
    { label: "Goodmayes", value: "goodmayes" },
    { label: "Goodwick", value: "goodwick" },
    { label: "Goole", value: "goole" },
    { label: "Gordon", value: "gordon" },
    { label: "Gorebridge", value: "gorebridge" },
    { label: "Gosport", value: "gosport" },
    { label: "Gourock", value: "gourock" },
    { label: "Grangemouth", value: "grangemouth" },
    { label: "Grange-over-Sands", value: "grange-over-sands" },
    { label: "Grantham", value: "grantham" },
    { label: "Grantown-on-Spey", value: "grantown-on-spey" },
    { label: "Gravesend", value: "gravesend" },
    { label: "Grays", value: "grays" },
    { label: "Grays Inn", value: "grays-inn" },
    { label: "Great Ilford", value: "great-ilford" },
    { label: "Great Missenden", value: "great-missenden" },
    { label: "Great Yarmouth", value: "great-yarmouth" },
    { label: "Green Park", value: "green-park" },
    { label: "Greenford", value: "greenford" },
    { label: "Greenhithe", value: "greenhithe" },
    { label: "Greenock", value: "greenock" },
    { label: "Greenwich", value: "greenwich" },
    { label: "Gretna", value: "gretna" },
    { label: "Grimsby", value: "grimsby" },
    { label: "Guernsey", value: "guernsey" },
    { label: "Guildford", value: "guildford" },
    { label: "Guisborough", value: "guisborough" },
    { label: "Gullane", value: "gullane" },
    { label: "Gunnislake", value: "gunnislake" },
    { label: "Hackney", value: "hackney" },
    { label: "Haddington", value: "haddington" },
    { label: "Hadley Wood", value: "hadley-wood" },
    { label: "Haggerston", value: "haggerston" },
    { label: "Hailsham", value: "hailsham" },
    { label: "Hainault", value: "hainault" },
    { label: "Halesowen", value: "halesowen" },
    { label: "Halesworth", value: "halesworth" },
    { label: "Halifax", value: "halifax" },
    { label: "Halkirk", value: "halkirk" },
    { label: "Halstead", value: "halstead" },
    { label: "Haltwhistle", value: "haltwhistle" },
    { label: "Hamilton", value: "hamilton" },
    { label: "Hammersmith", value: "hammersmith" },
    { label: "Hampstead", value: "hampstead" },
    { label: "Hampton", value: "hampton" },
    { label: "Hampton Hill", value: "hampton-hill" },
    { label: "Hampton Wick", value: "hampton-wick" },
    { label: "Hanwell", value: "hanwell" },
    { label: "Harefield", value: "harefield" },
    { label: "Haringey", value: "haringey" },
    { label: "Harlech", value: "harlech" },
    { label: "Harlesden", value: "harlesden" },
    { label: "Harleston", value: "harleston" },
    { label: "Harlington", value: "harlington" },
    { label: "Harlow", value: "harlow" },
    { label: "Harmondsworth", value: "harmondsworth" },
    { label: "Harold Hill", value: "harold-hill" },
    { label: "Harold Wood", value: "harold-wood" },
    { label: "Harpenden", value: "harpenden" },
    { label: "Harrogate", value: "harrogate" },
    { label: "Harrow", value: "harrow" },
    { label: "Hartfield", value: "hartfield" },
    { label: "Hartlepool", value: "hartlepool" },
    { label: "Harwich", value: "harwich" },
    { label: "Haslemere", value: "haslemere" },
    { label: "Hassocks", value: "hassocks" },
    { label: "Hastings", value: "hastings" },
    { label: "Hatfield", value: "hatfield" },
    { label: "Hatton Garden", value: "hatton-garden" },
    { label: "Havant", value: "havant" },
    { label: "Haverfordwest", value: "haverfordwest" },
    { label: "Haverhill", value: "haverhill" },
    { label: "Havering atte Bower", value: "havering-atte-bower" },
    { label: "Hawes", value: "hawes" },
    { label: "Hawick", value: "hawick" },
    { label: "Hayes", value: "hayes" },
    { label: "Hayle", value: "hayle" },
    { label: "Hayling Island", value: "hayling-island" },
    { label: "Haymarket", value: "haymarket" },
    { label: "Haywards Heath", value: "haywards-heath" },
    { label: "Heanor", value: "heanor" },
    { label: "Heathfield", value: "heathfield" },
    { label: "Heathrow", value: "heathrow" },
    { label: "Hebburn", value: "hebburn" },
    { label: "Hebden Bridge", value: "hebden-bridge" },
    { label: "Heckmondwike", value: "heckmondwike" },
    { label: "Helensburgh", value: "helensburgh" },
    { label: "Helmsdale", value: "helmsdale" },
    { label: "Helston", value: "helston" },
    { label: "Hemel Hempstead", value: "hemel-hempstead" },
    { label: "Hendon", value: "hendon" },
    { label: "Henfield", value: "henfield" },
    { label: "Hengoed", value: "hengoed" },
    { label: "Henley-in-Arden", value: "henley-in-arden" },
    { label: "Henley-on-Thames", value: "henley-on-thames" },
    { label: "Henlow", value: "henlow" },
    { label: "Hereford", value: "hereford" },
    { label: "Heriot", value: "heriot" },
    { label: "Herne Bay", value: "herne-bay" },
    { label: "Herne Hill", value: "herne-hill" },
    { label: "Hertford", value: "hertford" },
    { label: "Hessle", value: "hessle" },
    { label: "Heston", value: "heston" },
    { label: "Hexham", value: "hexham" },
    { label: "Heywood", value: "heywood" },
    { label: "High Peak", value: "high-peak" },
    { label: "High Wycombe", value: "high-wycombe" },
    { label: "Highbridge", value: "highbridge" },
    { label: "Highbury", value: "highbury" },
    { label: "Highgate", value: "highgate" },
    { label: "Hillingdon", value: "hillingdon" },
    { label: "Hillsborough", value: "hillsborough" },
    { label: "Hinckley", value: "hinckley" },
    { label: "Hindhead", value: "hindhead" },
    { label: "Hinton St George", value: "hinton-st-george" },
    { label: "Hitchin", value: "hitchin" },
    { label: "Hither Green", value: "hither-green" },
    { label: "Hockley", value: "hockley" },
    { label: "Hoddesdon", value: "hoddesdon" },
    { label: "Holborn", value: "holborn" },
    { label: "Holland Park", value: "holland-park" },
    { label: "Holloway", value: "holloway" },
    { label: "Holmfirth", value: "holmfirth" },
    { label: "Holmrook", value: "holmrook" },
    { label: "Holsworthy", value: "holsworthy" },
    { label: "Holt", value: "holt" },
    { label: "Holyhead", value: "holyhead" },
    { label: "Holywell", value: "holywell" },
    { label: "Holywood", value: "holywood" },
    { label: "Homerton", value: "homerton" },
    { label: "Honiton", value: "honiton" },
    { label: "Honor Oak", value: "honor-oak" },
    { label: "Hook", value: "hook" },
    { label: "Hope Valley", value: "hope-valley" },
    { label: "Horley", value: "horley" },
    { label: "Horncastle", value: "horncastle" },
    { label: "Hornchurch", value: "hornchurch" },
    { label: "Hornsea", value: "hornsea" },
    { label: "Hornsey", value: "hornsey" },
    { label: "Horsham", value: "horsham" },
    { label: "Houghton le Spring", value: "houghton-le-spring" },
    { label: "Hounslow", value: "hounslow" },
    { label: "Hove", value: "hove" },
    { label: "Hoxton", value: "hoxton" },
    { label: "Huddersfield", value: "huddersfield" },
    { label: "Hull", value: "hull" },
    { label: "Humbie", value: "humbie" },
    { label: "Hungerford", value: "hungerford" },
    { label: "Hunstanton", value: "hunstanton" },
    { label: "Huntingdon", value: "huntingdon" },
    { label: "Huntly", value: "huntly" },
    { label: "Hyde", value: "hyde" },
    { label: "Hyde Park", value: "hyde-park" },
    { label: "Hyde Park Corner", value: "hyde-park-corner" },
    { label: "Hythe", value: "hythe" },
    { label: "Ibstock", value: "ibstock" },
    { label: "Ilford", value: "ilford" },
    { label: "Ilfracombe", value: "ilfracombe" },
    { label: "Ilkeston", value: "ilkeston" },
    { label: "Ilkley", value: "ilkley" },
    { label: "Ilminster", value: "ilminster" },
    { label: "Immingham", value: "immingham" },
    { label: "Ingatestone", value: "ingatestone" },
    { label: "Innerleithen", value: "innerleithen" },
    { label: "Insch", value: "insch" },
    { label: "Inveraray", value: "inveraray" },
    { label: "Invergarry", value: "invergarry" },
    { label: "Invergordon", value: "invergordon" },
    { label: "Inverkeithing", value: "inverkeithing" },
    { label: "Inverness", value: "inverness" },
    { label: "Inverurie", value: "inverurie" },
    { label: "Ipswich", value: "ipswich" },
    { label: "Irvine", value: "irvine" },
    { label: "Isle of Arran", value: "isle-of-arran" },
    { label: "Isle of Barra", value: "isle-of-barra" },
    { label: "Isle of Benbecula", value: "isle-of-benbecula" },
    { label: "Isle of Bute", value: "isle-of-bute" },
    { label: "Isle of Canna", value: "isle-of-canna" },
    { label: "Isle of Coll", value: "isle-of-coll" },
    { label: "Isle of Colonsay", value: "isle-of-colonsay" },
    { label: "Isle of Cumbrae", value: "isle-of-cumbrae" },
    { label: "Isle of Dogs", value: "isle-of-dogs" },
    { label: "Isle of Eigg", value: "isle-of-eigg" },
    { label: "Isle of Gigha", value: "isle-of-gigha" },
    { label: "Isle of Harris", value: "isle-of-harris" },
    { label: "Isle of Iona", value: "isle-of-iona" },
    { label: "Isle of Islay", value: "isle-of-islay" },
    { label: "Isle of Jura", value: "isle-of-jura" },
    { label: "Isle of Lewis", value: "isle-of-lewis" },
    { label: "Isle of Man", value: "isle-of-man" },
    { label: "Isle of Mull", value: "isle-of-mull" },
    { label: "Isle of North Uist", value: "isle-of-north-uist" },
    { label: "Isle of Rum", value: "isle-of-rum" },
    { label: "Isle of Scalpay", value: "isle-of-scalpay" },
    { label: "Isle of Skye", value: "isle-of-skye" },
    { label: "Isle of South Uist", value: "isle-of-south-uist" },
    { label: "Isle of Tiree", value: "isle-of-tiree" },
    { label: "Isles of Scilly", value: "isles-of-scilly" },
    { label: "Isleworth", value: "isleworth" },
    { label: "Islington", value: "islington" },
    { label: "Iver", value: "iver" },
    { label: "Ivybridge", value: "ivybridge" },
    { label: "Jarrow", value: "jarrow" },
    { label: "Jedburgh", value: "jedburgh" },
    { label: "Jersey", value: "jersey" },
    { label: "Johnstone", value: "johnstone" },
    { label: "Juniper Green", value: "juniper-green" },
    { label: "Keighley", value: "keighley" },
    { label: "Keith", value: "keith" },
    { label: "Kelso", value: "kelso" },
    { label: "Kelty", value: "kelty" },
    { label: "Kendal", value: "kendal" },
    { label: "Kenilworth", value: "kenilworth" },
    { label: "Kenley", value: "kenley" },
    { label: "Kennington", value: "kennington" },
    { label: "Kensal Green", value: "kensal-green" },
    { label: "Kensal Rise", value: "kensal-rise" },
    { label: "Kensington", value: "kensington" },
    { label: "Kentish Town", value: "kentish-town" },
    { label: "Kenton", value: "kenton" },
    { label: "Keston", value: "keston" },
    { label: "Keswick", value: "keswick" },
    { label: "Kettering", value: "kettering" },
    { label: "Kew", value: "kew" },
    { label: "Kidderminster", value: "kidderminster" },
    { label: "Kidlington", value: "kidlington" },
    { label: "Kidwelly", value: "kidwelly" },
    { label: "Kilbirnie", value: "kilbirnie" },
    { label: "Kilburn", value: "kilburn" },
    { label: "Kilgetty", value: "kilgetty" },
    { label: "Killin", value: "killin" },
    { label: "Kilmacolm", value: "kilmacolm" },
    { label: "Kilmarnock", value: "kilmarnock" },
    { label: "Kilwinning", value: "kilwinning" },
    { label: "Kinbrace", value: "kinbrace" },
    { label: "Kings Cross", value: "kings-cross" },
    { label: "Kings Langley", value: "kings-langley" },
    { label: "King's Lynn", value: "kings-lynn" },
    { label: "Kingsbridge", value: "kingsbridge" },
    { label: "Kingsbury", value: "kingsbury" },
    { label: "Kingsland", value: "kingsland" },
    { label: "Kingston upon Thames", value: "kingston-upon-thames" },
    { label: "Kingston Vale", value: "kingston-vale" },
    { label: "Kingswinford", value: "kingswinford" },
    { label: "Kington", value: "kington" },
    { label: "Kingussie", value: "kingussie" },
    { label: "Kinlochleven", value: "kinlochleven" },
    { label: "Kinross", value: "kinross" },
    { label: "Kirkby Stephen", value: "kirkby-stephen" },
    { label: "Kirkby-in-Furness", value: "kirkby-in-furness" },
    { label: "Kirkcaldy", value: "kirkcaldy" },
    { label: "Kirkcudbright", value: "kirkcudbright" },
    { label: "Kirkliston", value: "kirkliston" },
    { label: "Kirknewton", value: "kirknewton" },
    { label: "Kirkwall", value: "kirkwall" },
    { label: "Kirriemuir", value: "kirriemuir" },
    { label: "Knaresborough", value: "knaresborough" },
    { label: "Knebworth", value: "knebworth" },
    { label: "Knighton", value: "knighton" },
    { label: "Knightsbridge", value: "knightsbridge" },
    { label: "Knottingley", value: "knottingley" },
    { label: "Knutsford", value: "knutsford" },
    { label: "Kyle", value: "kyle" },
    { label: "Lairg", value: "lairg" },
    { label: "Lambeth", value: "lambeth" },
    { label: "Lampeter", value: "lampeter" },
    { label: "Lanark", value: "lanark" },
    { label: "Lancaster", value: "lancaster" },
    { label: "Lancaster Gate", value: "lancaster-gate" },
    { label: "Lancing", value: "lancing" },
    { label: "Langholm", value: "langholm" },
    { label: "Langport", value: "langport" },
    { label: "Larbert", value: "larbert" },
    { label: "Largs", value: "largs" },
    { label: "Larkhall", value: "larkhall" },
    { label: "Larne", value: "larne" },
    { label: "Lasswade", value: "lasswade" },
    { label: "Latheron", value: "latheron" },
    { label: "Lauder", value: "lauder" },
    { label: "Launceston", value: "launceston" },
    { label: "Laurencekirk", value: "laurencekirk" },
    { label: "lcester", value: "lcester" },
    { label: "Leamington Spa", value: "leamington-spa" },
    { label: "Leatherhead", value: "leatherhead" },
    { label: "Lechlade", value: "lechlade" },
    { label: "Ledbury", value: "ledbury" },
    { label: "Leeds", value: "leeds" },
    { label: "Leek", value: "leek" },
    { label: "Lee-on-the-Solent", value: "lee-on-the-solent" },
    { label: "Leicester", value: "leicester" },
    { label: "Leicester Square", value: "leicester-square" },
    { label: "Leigh", value: "leigh" },
    { label: "Leigh-on-Sea", value: "leigh-on-sea" },
    { label: "Leighton Buzzard", value: "leighton-buzzard" },
    { label: "Leiston", value: "leiston" },
    { label: "Leominster", value: "leominster" },
    { label: "Letchworth", value: "letchworth" },
    { label: "Leven", value: "leven" },
    { label: "Lewes", value: "lewes" },
    { label: "Lewisham", value: "lewisham" },
    { label: "lexandria", value: "lexandria" },
    { label: "Leyburn", value: "leyburn" },
    { label: "Leyland", value: "leyland" },
    { label: "Leyton", value: "leyton" },
    { label: "Leytonstone", value: "leytonstone" },
    { label: "Leytonstone & Wanstead", value: "leytonstone-and-wanstead" },
    { label: "Lichfield", value: "lichfield" },
    { label: "Lifton", value: "lifton" },
    { label: "Lightwater", value: "lightwater" },
    { label: "Limavady", value: "limavady" },
    { label: "Limehouse", value: "limehouse" },
    { label: "Lincoln", value: "lincoln" },
    { label: "Lingfield", value: "lingfield" },
    { label: "Linlithgow", value: "linlithgow" },
    { label: "Liphook", value: "liphook" },
    { label: "Lisburn", value: "lisburn" },
    { label: "Liskeard", value: "liskeard" },
    { label: "Liss", value: "liss" },
    { label: "Little Heath", value: "little-heath" },
    { label: "Little Ilford", value: "little-ilford" },
    { label: "Little Venice", value: "little-venice" },
    { label: "Littleborough", value: "littleborough" },
    { label: "Littlehampton", value: "littlehampton" },
    { label: "Liverpool", value: "liverpool" },
    { label: "Liverpool Street", value: "liverpool-street" },
    { label: "Liversedge", value: "liversedge" },
    { label: "Livingston", value: "livingston" },
    { label: "Llanarth", value: "llanarth" },
    { label: "Llanbedr", value: "llanbedr" },
    { label: "Llanbedrgoch", value: "llanbedrgoch" },
    { label: "Llanbrynmair", value: "llanbrynmair" },
    { label: "Llandeilo", value: "llandeilo" },
    { label: "Llandinam", value: "llandinam" },
    { label: "Llandovery", value: "llandovery" },
    { label: "Llandrindod Wells", value: "llandrindod-wells" },
    { label: "Llandudno", value: "llandudno" },
    { label: "Llandudno Junction", value: "llandudno-junction" },
    { label: "Llandysul", value: "llandysul" },
    { label: "Llanelli", value: "llanelli" },
    { label: "Llanerchymedd", value: "llanerchymedd" },
    { label: "Llanfechain", value: "llanfechain" },
    { label: "Llanfyllin", value: "llanfyllin" },
    { label: "Llanfyrnach", value: "llanfyrnach" },
    { label: "Llangadog", value: "llangadog" },
    { label: "Llangammarch Wells", value: "llangammarch-wells" },
    { label: "Llanidloes", value: "llanidloes" },
    { label: "Llanon", value: "llanon" },
    { label: "Llanrhystud", value: "llanrhystud" },
    { label: "Llansantffraid", value: "llansantffraid" },
    { label: "Llantwit Major", value: "llantwit-major" },
    { label: "Llanwrda", value: "llanwrda" },
    { label: "Llanwrtyd Wells", value: "llanwrtyd-wells" },
    { label: "Llanybydder", value: "llanybydder" },
    { label: "Llanymynech", value: "llanymynech" },
    { label: "Loanhead", value: "loanhead" },
    { label: "Lochailort", value: "lochailort" },
    { label: "Lochearnhead", value: "lochearnhead" },
    { label: "Lochgelly", value: "lochgelly" },
    { label: "Lochgilphead", value: "lochgilphead" },
    { label: "Lochwinnoch", value: "lochwinnoch" },
    { label: "Lockerbie", value: "lockerbie" },
    { label: "London", value: "london" },
    { label: "London Bridge", value: "london-bridge" },
    { label: "London Wall", value: "london-wall" },
    { label: "Longfield", value: "longfield" },
    { label: "Longford", value: "longford" },
    { label: "Longhope", value: "longhope" },
    { label: "Longniddry", value: "longniddry" },
    { label: "Looe", value: "looe" },
    { label: "Lossiemouth", value: "lossiemouth" },
    { label: "Lostwithiel", value: "lostwithiel" },
    { label: "Loughborough", value: "loughborough" },
    { label: "Loughton", value: "loughton" },
    { label: "Louth", value: "louth" },
    { label: "Lowestoft", value: "lowestoft" },
    { label: "Ludlow", value: "ludlow" },
    { label: "Luton", value: "luton" },
    { label: "Lutterworth", value: "lutterworth" },
    { label: "Lybster", value: "lybster" },
    { label: "Lydbrook", value: "lydbrook" },
    { label: "Lydbury North", value: "lydbury-north" },
    { label: "Lydney", value: "lydney" },
    { label: "Lyme Regis", value: "lyme-regis" },
    { label: "Lymington", value: "lymington" },
    { label: "Lymm", value: "lymm" },
    { label: "Lyndhurst", value: "lyndhurst" },
    { label: "Lynmouth", value: "lynmouth" },
    { label: "Lynton", value: "lynton" },
    { label: "Lytham St Annes", value: "lytham-st-annes" },
    { label: "Mablethorpe", value: "mablethorpe" },
    { label: "Macclesfield", value: "macclesfield" },
    { label: "Macduff", value: "macduff" },
    { label: "Machynlleth", value: "machynlleth" },
    { label: "Maesteg", value: "maesteg" },
    { label: "Maida Vale", value: "maida-vale" },
    { label: "Maidenhead", value: "maidenhead" },
    { label: "Maidstone", value: "maidstone" },
    { label: "Maldon", value: "maldon" },
    { label: "Mallaig", value: "mallaig" },
    { label: "Malmesbury", value: "malmesbury" },
    { label: "Malpas", value: "malpas" },
    { label: "Malton", value: "malton" },
    { label: "Malvern", value: "malvern" },
    { label: "Manningtree", value: "manningtree" },
    { label: "Manor Park", value: "manor-park" },
    { label: "Mansfield", value: "mansfield" },
    { label: "Marazion", value: "marazion" },
    { label: "Marble Arch", value: "marble-arch" },
    { label: "March", value: "march" },
    { label: "Margate", value: "margate" },
    { label: "Market Drayton", value: "market-drayton" },
    { label: "Market Harborough", value: "market-harborough" },
    { label: "Market Rasen", value: "market-rasen" },
    { label: "Markfield", value: "markfield" },
    { label: "Marlborough", value: "marlborough" },
    { label: "Marlow", value: "marlow" },
    { label: "Martock", value: "martock" },
    { label: "Marylebone", value: "marylebone" },
    { label: "Maryport", value: "maryport" },
    { label: "Matlock", value: "matlock" },
    { label: "Mauchline", value: "mauchline" },
    { label: "Maybole", value: "maybole" },
    { label: "Mayfair", value: "mayfair" },
    { label: "Mayfield", value: "mayfield" },
    { label: "Meifod", value: "meifod" },
    { label: "Melksham", value: "melksham" },
    { label: "Melrose", value: "melrose" },
    { label: "Melton Constable", value: "melton-constable" },
    { label: "Melton Mowbray", value: "melton-mowbray" },
    { label: "Menstrie", value: "menstrie" },
    { label: "Merriott", value: "merriott" },
    { label: "Merthyr Tydfil", value: "merthyr-tydfil" },
    { label: "Merton", value: "merton" },
    { label: "Mexborough", value: "mexborough" },
    { label: "Middlesbrough", value: "middlesbrough" },
    { label: "Middlewich", value: "middlewich" },
    { label: "Midhurst", value: "midhurst" },
    { label: "Mile End", value: "mile-end" },
    { label: "Milford Haven", value: "milford-haven" },
    { label: "Mill Hill", value: "mill-hill" },
    { label: "Millom", value: "millom" },
    { label: "Milltimber", value: "milltimber" },
    { label: "Millwall", value: "millwall" },
    { label: "Milnthorpe", value: "milnthorpe" },
    { label: "Milton Keynes", value: "milton-keynes" },
    { label: "Mindrum", value: "mindrum" },
    { label: "Minehead", value: "minehead" },
    { label: "Mirfield", value: "mirfield" },
    { label: "Mitcham", value: "mitcham" },
    { label: "Mitcheldean", value: "mitcheldean" },
    { label: "Moffat", value: "moffat" },
    { label: "Mold", value: "mold" },
    { label: "Monmouth", value: "monmouth" },
    { label: "Montacute", value: "montacute" },
    { label: "Montgomery", value: "montgomery" },
    { label: "Montrose", value: "montrose" },
    { label: "Monument", value: "monument" },
    { label: "Moor Row", value: "moor-row" },
    { label: "Moorgate", value: "moorgate" },
    { label: "Morden", value: "morden" },
    { label: "Morecambe", value: "morecambe" },
    { label: "Moreton-in-Marsh", value: "moreton-in-marsh" },
    { label: "Morpeth", value: "morpeth" },
    { label: "Mortlake", value: "mortlake" },
    { label: "Motherwell", value: "motherwell" },
    { label: "Mottingham", value: "mottingham" },
    { label: "Mountain Ash", value: "mountain-ash" },
    { label: "Much Hadham", value: "much-hadham" },
    { label: "Much Wenlock", value: "much-wenlock" },
    { label: "Muir of Ord", value: "muir-of-ord" },
    { label: "Munlochy", value: "munlochy" },
    { label: "Musselburgh", value: "musselburgh" },
    { label: "Muswell Hill", value: "muswell-hill" },
    { label: "Nairn", value: "nairn" },
    { label: "Nantwich", value: "nantwich" },
    { label: "Narberth", value: "narberth" },
    { label: "Neath", value: "neath" },
    { label: "Nelson", value: "nelson" },
    { label: "Neston", value: "neston" },
    { label: "Nethy Bridge", value: "nethy-bridge" },
    { label: "New Malden", value: "new-malden" },
    { label: "New Milton", value: "new-milton" },
    { label: "New Quay", value: "new-quay" },
    { label: "New Romney", value: "new-romney" },
    { label: "New Tredegar", value: "new-tredegar" },
    { label: "Newark-on-Trent", value: "newark-on-trent" },
    { label: "Newbiggin-by-the-Sea", value: "newbiggin-by-the-sea" },
    { label: "Newbridge", value: "newbridge" },
    { label: "Newbury", value: "newbury" },
    { label: "Newbury Park", value: "newbury-park" },
    { label: "Newcastle", value: "newcastle" },
    { label: "Newcastle Emlyn", value: "newcastle-emlyn" },
    { label: "Newcastle upon Tyne", value: "newcastle-upon-tyne" },
    { label: "Newcastleton", value: "newcastleton" },
    { label: "Newent", value: "newent" },
    { label: "Newhaven", value: "newhaven" },
    { label: "Newmarket", value: "newmarket" },
    { label: "Newmilns", value: "newmilns" },
    { label: "Newnham", value: "newnham" },
    { label: "Newport", value: "newport" },
    { label: "Newport Pagnell", value: "newport-pagnell" },
    { label: "Newport-on-Tay", value: "newport-on-tay" },
    { label: "Newquay", value: "newquay" },
    { label: "Newton Abbot", value: "newton-abbot" },
    { label: "Newton Aycliffe", value: "newton-aycliffe" },
    { label: "Newton Stewart", value: "newton-stewart" },
    { label: "Newton-le-Willows", value: "newton-le-willows" },
    { label: "Newtonmore", value: "newtonmore" },
    { label: "Newtown", value: "newtown" },
    { label: "Normanton", value: "normanton" },
    { label: "North Berwick", value: "north-berwick" },
    { label: "North Ferriby", value: "north-ferriby" },
    { label: "North Finchley", value: "north-finchley" },
    { label: "North Kensington", value: "north-kensington" },
    { label: "North Shields", value: "north-shields" },
    { label: "North Tawton", value: "north-tawton" },
    { label: "North Walsham", value: "north-walsham" },
    { label: "North Woolwich", value: "north-woolwich" },
    { label: "Northallerton", value: "northallerton" },
    { label: "Northampton", value: "northampton" },
    { label: "Northolt", value: "northolt" },
    { label: "Northwich", value: "northwich" },
    { label: "Northwood", value: "northwood" },
    { label: "Norton Folgate", value: "norton-folgate" },
    { label: "Norwich", value: "norwich" },
    { label: "Notting Hill", value: "notting-hill" },
    { label: "Nottingham", value: "nottingham" },
    { label: "Nuneaton", value: "nuneaton" },
    { label: "Oakham", value: "oakham" },
    { label: "Oban", value: "oban" },
    { label: "Okehampton", value: "okehampton" },
    { label: "Old Ford", value: "old-ford" },
    { label: "Old Street", value: "old-street" },
    { label: "Oldbury", value: "oldbury" },
    { label: "Oldham", value: "oldham" },
    { label: "Olney", value: "olney" },
    { label: "Olympia", value: "olympia" },
    { label: "Ongar", value: "ongar" },
    { label: "Orkney", value: "orkney" },
    { label: "Ormskirk", value: "ormskirk" },
    { label: "Orpington", value: "orpington" },
    { label: "Ossett", value: "ossett" },
    { label: "Osterley", value: "osterley" },
    { label: "Oswestry", value: "oswestry" },
    { label: "Otley", value: "otley" },
    { label: "Ottery St Mary", value: "ottery-st-mary" },
    { label: "Oxford", value: "oxford" },
    { label: "Oxford Circus", value: "oxford-circus" },
    { label: "Oxford Street", value: "oxford-street" },
    { label: "Oxted", value: "oxted" },
    { label: "Paddington", value: "paddington" },
    { label: "Padstow", value: "padstow" },
    { label: "Paignton", value: "paignton" },
    { label: "Paisley", value: "paisley" },
    { label: "Palmers Green", value: "palmers-green" },
    { label: "Par", value: "par" },
    { label: "Park Lane", value: "park-lane" },
    { label: "Parsons Green", value: "parsons-green" },
    { label: "Pathhead", value: "pathhead" },
    { label: "Peacehaven", value: "peacehaven" },
    { label: "Peckham", value: "peckham" },
    { label: "Peebles", value: "peebles" },
    { label: "Pembroke", value: "pembroke" },
    { label: "Penarth", value: "penarth" },
    { label: "Pencader", value: "pencader" },
    { label: "Penge", value: "penge" },
    { label: "Penicuik", value: "penicuik" },
    { label: "Penrith", value: "penrith" },
    { label: "Penryn", value: "penryn" },
    { label: "Pentonville", value: "pentonville" },
    { label: "Pentre", value: "pentre" },
    { label: "Penzance", value: "penzance" },
    { label: "Perivale", value: "perivale" },
    { label: "Perranporth", value: "perranporth" },
    { label: "Pershore", value: "pershore" },
    { label: "Perth", value: "perth" },
    { label: "Peterborough", value: "peterborough" },
    { label: "Peterculter", value: "peterculter" },
    { label: "Peterhead", value: "peterhead" },
    { label: "Peterlee", value: "peterlee" },
    { label: "Petersfield", value: "petersfield" },
    { label: "Petworth", value: "petworth" },
    { label: "Pevensey", value: "pevensey" },
    { label: "Pewsey", value: "pewsey" },
    { label: "Piccadilly", value: "piccadilly" },
    { label: "Piccadilly Circus", value: "piccadilly-circus" },
    { label: "Pickering", value: "pickering" },
    { label: "Pimlico", value: "pimlico" },
    { label: "Pinner", value: "pinner" },
    { label: "Pitlochry", value: "pitlochry" },
    { label: "Plaistow", value: "plaistow" },
    { label: "Plockton", value: "plockton" },
    { label: "Plumstead", value: "plumstead" },
    { label: "Plymouth", value: "plymouth" },
    { label: "Polegate", value: "polegate" },
    { label: "Pontefract", value: "pontefract" },
    { label: "Pontyclun", value: "pontyclun" },
    { label: "Pontypool", value: "pontypool" },
    { label: "Pontypridd", value: "pontypridd" },
    { label: "Poole", value: "poole" },
    { label: "Poplar", value: "poplar" },
    { label: "Port Glasgow", value: "port-glasgow" },
    { label: "Port Isaac", value: "port-isaac" },
    { label: "Port Talbot", value: "port-talbot" },
    { label: "Porth", value: "porth" },
    { label: "Porthcawl", value: "porthcawl" },
    { label: "Portland", value: "portland" },
    { label: "Portree", value: "portree" },
    { label: "Portsmouth", value: "portsmouth" },
    { label: "Potters Bar", value: "potters-bar" },
    { label: "Poulton-Le-Fylde", value: "poulton-le-fylde" },
    { label: "Prenton", value: "prenton" },
    { label: "Prescot", value: "prescot" },
    { label: "Presteigne", value: "presteigne" },
    { label: "Preston", value: "preston" },
    { label: "Prestonpans", value: "prestonpans" },
    { label: "Prestwick", value: "prestwick" },
    { label: "Primrose Hill", value: "primrose-hill" },
    { label: "Princes Risborough", value: "princes-risborough" },
    { label: "Prudhoe", value: "prudhoe" },
    { label: "Pudsey", value: "pudsey" },
    { label: "Pulborough", value: "pulborough" },
    { label: "Purfleet", value: "purfleet" },
    { label: "Purley", value: "purley" },
    { label: "Putney", value: "putney" },
    { label: "Queenborough", value: "queenborough" },
    { label: "Queens Park", value: "queens-park" },
    { label: "Queensway", value: "queensway" },
    { label: "Radlett", value: "radlett" },
    { label: "Radstock", value: "radstock" },
    { label: "Rainham", value: "rainham" },
    { label: "Ramsgate", value: "ramsgate" },
    { label: "Ratcliff", value: "ratcliff" },
    { label: "Ravenglass", value: "ravenglass" },
    { label: "Ravenscourt Park", value: "ravenscourt-park" },
    { label: "Rayleigh", value: "rayleigh" },
    { label: "Reading", value: "reading" },
    { label: "Redbridge", value: "redbridge" },
    { label: "Redcar", value: "redcar" },
    { label: "Redditch", value: "redditch" },
    { label: "Redhill", value: "redhill" },
    { label: "Redruth", value: "redruth" },
    { label: "Regents Park", value: "regents-park" },
    { label: "Reigate", value: "reigate" },
    { label: "Renfrew", value: "renfrew" },
    { label: "Retford", value: "retford" },
    { label: "Rhayader", value: "rhayader" },
    { label: "Richmond", value: "richmond" },
    { label: "Richmond-upon-Thames", value: "richmond-upon-thames" },
    { label: "Rickmansworth", value: "rickmansworth" },
    { label: "Riding Mill", value: "riding-mill" },
    { label: "Ringwood", value: "ringwood" },
    { label: "Ripley", value: "ripley" },
    { label: "Ripon", value: "ripon" },
    { label: "Robertsbridge", value: "robertsbridge" },
    { label: "Rochdale", value: "rochdale" },
    { label: "Rochester", value: "rochester" },
    { label: "Rochford", value: "rochford" },
    { label: "Roehampton", value: "roehampton" },
    { label: "Rogart", value: "rogart" },
    { label: "Romford", value: "romford" },
    { label: "Romney Marsh", value: "romney-marsh" },
    { label: "Romsey", value: "romsey" },
    { label: "Rosewell", value: "rosewell" },
    { label: "Roslin", value: "roslin" },
    { label: "Rossendale", value: "rossendale" },
    { label: "Ross-on-Wye", value: "ross-on-wye" },
    { label: "Rotherham", value: "rotherham" },
    { label: "Rotherhithe", value: "rotherhithe" },
    { label: "Rowland's Castle", value: "rowlands-castle" },
    { label: "Rowlands Gill", value: "rowlands-gill" },
    { label: "Rowley Regis", value: "rowley-regis" },
    { label: "Roy Bridge", value: "roy-bridge" },
    { label: "Royston", value: "royston" },
    { label: "Ruardean", value: "ruardean" },
    { label: "Rugby", value: "rugby" },
    { label: "Rugeley", value: "rugeley" },
    { label: "Ruislip", value: "ruislip" },
    { label: "Runcorn", value: "runcorn" },
    { label: "Rush Green", value: "rush-green" },
    { label: "Rushden", value: "rushden" },
    { label: "Ryde", value: "ryde" },
    { label: "Rye", value: "rye" },
    { label: "Ryton", value: "ryton" },
    { label: "Saffron Walden", value: "saffron-walden" },
    { label: "Salcombe", value: "salcombe" },
    { label: "Sale", value: "sale" },
    { label: "Salford", value: "salford" },
    { label: "Salisbury", value: "salisbury" },
    { label: "Saltash", value: "saltash" },
    { label: "Saltburn-by-the-Sea", value: "saltburn-by-the-sea" },
    { label: "Saltcoats", value: "saltcoats" },
    { label: "Sandbach", value: "sandbach" },
    { label: "Sandhurst", value: "sandhurst" },
    { label: "Sandown", value: "sandown" },
    { label: "Sandringham", value: "sandringham" },
    { label: "Sandwich", value: "sandwich" },
    { label: "Sandy", value: "sandy" },
    { label: "Sanquhar", value: "sanquhar" },
    { label: "Saundersfoot", value: "saundersfoot" },
    { label: "Sawbridgeworth", value: "sawbridgeworth" },
    { label: "Saxmundham", value: "saxmundham" },
    { label: "Scarborough", value: "scarborough" },
    { label: "Scotland", value: "scotland" },
    { label: "Scunthorpe", value: "scunthorpe" },
    { label: "Seaford", value: "seaford" },
    { label: "Seaham", value: "seaham" },
    { label: "Seahouses", value: "seahouses" },
    { label: "Seascale", value: "seascale" },
    { label: "Seaton", value: "seaton" },
    { label: "Seaview", value: "seaview" },
    { label: "Sedbergh", value: "sedbergh" },
    { label: "Selby", value: "selby" },
    { label: "Selkirk", value: "selkirk" },
    { label: "Settle", value: "settle" },
    { label: "Seven Kings", value: "seven-kings" },
    { label: "Sevenoaks", value: "sevenoaks" },
    { label: "Shadwell", value: "shadwell" },
    { label: "Shaftesbury", value: "shaftesbury" },
    { label: "Shanklin", value: "shanklin" },
    { label: "Sheerness", value: "sheerness" },
    { label: "Sheffield", value: "sheffield" },
    { label: "Shefford", value: "shefford" },
    { label: "Shepherds Bush", value: "shepherds-bush" },
    { label: "Shepperton", value: "shepperton" },
    { label: "Shepton Mallet", value: "shepton-mallet" },
    { label: "Sherborne", value: "sherborne" },
    { label: "Sheringham", value: "sheringham" },
    { label: "Shetland", value: "shetland" },
    { label: "Shifnal", value: "shifnal" },
    { label: "Shildon", value: "shildon" },
    { label: "Shipley", value: "shipley" },
    { label: "Shipston-on-Stour", value: "shipston-on-stour" },
    { label: "Shoreditch", value: "shoreditch" },
    { label: "Shoreham-by-Sea", value: "shoreham-by-sea" },
    { label: "Shotts", value: "shotts" },
    { label: "Shrewsbury", value: "shrewsbury" },
    { label: "Sidcup", value: "sidcup" },
    { label: "Sidmouth", value: "sidmouth" },
    { label: "Silvertown", value: "silvertown" },
    { label: "Sittingbourne", value: "sittingbourne" },
    { label: "Skegness", value: "skegness" },
    { label: "Skelmersdale", value: "skelmersdale" },
    { label: "Skelmorlie", value: "skelmorlie" },
    { label: "Skipton", value: "skipton" },
    { label: "Sleaford", value: "sleaford" },
    { label: "Slough", value: "slough" },
    { label: "Smethwick", value: "smethwick" },
    { label: "Smithfield", value: "smithfield" },
    { label: "Snaresbrook", value: "snaresbrook" },
    { label: "Snodland", value: "snodland" },
    { label: "Soho", value: "soho" },
    { label: "Solihull", value: "solihull" },
    { label: "Somerton", value: "somerton" },
    { label: "South Bank", value: "south-bank" },
    { label: "South Brent", value: "south-brent" },
    { label: "South Croydon", value: "south-croydon" },
    { label: "South Kensington", value: "south-kensington" },
    { label: "South Molton", value: "south-molton" },
    { label: "South Norwood", value: "south-norwood" },
    { label: "South Ockendon", value: "south-ockendon" },
    { label: "South Petherton", value: "south-petherton" },
    { label: "South Ruislip", value: "south-ruislip" },
    { label: "South Shields", value: "south-shields" },
    { label: "South Woodford", value: "south-woodford" },
    { label: "Southall", value: "southall" },
    { label: "Southam", value: "southam" },
    { label: "Southampton", value: "southampton" },
    { label: "Southend-on-Sea", value: "southend-on-sea" },
    { label: "Southgate", value: "southgate" },
    { label: "Southminster", value: "southminster" },
    { label: "Southport", value: "southport" },
    { label: "Southsea", value: "southsea" },
    { label: "Southwark", value: "southwark" },
    { label: "Southwell", value: "southwell" },
    { label: "Southwold", value: "southwold" },
    { label: "Sowerby Bridge", value: "sowerby-bridge" },
    { label: "Spalding", value: "spalding" },
    { label: "Spean Bridge", value: "spean-bridge" },
    { label: "Spennymoor", value: "spennymoor" },
    { label: "Spilsby", value: "spilsby" },
    { label: "Spitalfields", value: "spitalfields" },
    { label: "St Agnes", value: "st-agnes" },
    { label: "St Albans", value: "st-albans" },
    { label: "St Andrews", value: "st-andrews" },
    { label: "St Austell", value: "st-austell" },
    { label: "St Bees", value: "st-bees" },
    { label: "St Columb", value: "st-columb" },
    { label: "St George in the East", value: "st-george-in-the-east" },
    { label: "St Helens", value: "st-helens" },
    { label: "St Ives", value: "st-ives" },
    { label: "St James's", value: "st-jamess" },
    { label: "St Johns Wood", value: "st-johns-wood" },
    { label: "St Katherines Dock", value: "st-katherines-dock" },
    { label: "St Leonards-on-Sea", value: "st-leonards-on-sea" },
    { label: "St Neots", value: "st-neots" },
    { label: "St Pauls", value: "st-pauls" },
    { label: "Stafford", value: "stafford" },
    { label: "Staines", value: "staines" },
    { label: "Stalybridge", value: "stalybridge" },
    { label: "Stamford", value: "stamford" },
    { label: "Stamford Hill", value: "stamford-hill" },
    { label: "Stanford-le-Hope", value: "stanford-le-hope" },
    { label: "Stanley", value: "stanley" },
    { label: "Stanmore", value: "stanmore" },
    { label: "Stansted", value: "stansted" },
    { label: "Stepney", value: "stepney" },
    { label: "Stepney Green", value: "stepney-green" },
    { label: "Stevenage", value: "stevenage" },
    { label: "Stevenston", value: "stevenston" },
    { label: "Steyning", value: "steyning" },
    { label: "Stirling", value: "stirling" },
    { label: "Stockbridge", value: "stockbridge" },
    { label: "Stockport", value: "stockport" },
    { label: "Stocksfield", value: "stocksfield" },
    { label: "Stockton-on-Tees", value: "stockton-on-tees" },
    { label: "Stockwell", value: "stockwell" },
    { label: "Stoke Newington", value: "stoke-newington" },
    { label: "Stoke-on-Trent", value: "stoke-on-trent" },
    { label: "Stoke-sub-Hamdon", value: "stoke-sub-hamdon" },
    { label: "Stone", value: "stone" },
    { label: "Stonehaven", value: "stonehaven" },
    { label: "Stonehouse", value: "stonehouse" },
    { label: "Stornoway", value: "stornoway" },
    { label: "Stourbridge", value: "stourbridge" },
    { label: "Stourport-on-Severn", value: "stourport-on-severn" },
    { label: "Stowmarket", value: "stowmarket" },
    { label: "Strand", value: "strand" },
    { label: "Stranraer", value: "stranraer" },
    { label: "Stratford", value: "stratford" },
    { label: "Stratford Langthorne", value: "stratford-langthorne" },
    { label: "Stratford le Bow", value: "stratford-le-bow" },
    { label: "Stratford-upon-Avon", value: "stratford-upon-avon" },
    { label: "Strathaven", value: "strathaven" },
    { label: "Strathcarron", value: "strathcarron" },
    { label: "Strathdon", value: "strathdon" },
    { label: "Strathpeffer", value: "strathpeffer" },
    { label: "Streatham", value: "streatham" },
    { label: "Street", value: "street" },
    { label: "Strome Ferry", value: "strome-ferry" },
    { label: "Stromness", value: "stromness" },
    { label: "Stroud", value: "stroud" },
    { label: "Studley", value: "studley" },
    { label: "Sturminster Newton", value: "sturminster-newton" },
    { label: "Sudbury", value: "sudbury" },
    { label: "Sudbury Hill", value: "sudbury-hill" },
    { label: "Sunbury-on-Thames", value: "sunbury-on-thames" },
    { label: "Sunderland", value: "sunderland" },
    { label: "Surbiton", value: "surbiton" },
    { label: "Sutton", value: "sutton" },
    { label: "Sutton Coldfield", value: "sutton-coldfield" },
    { label: "Sutton-in-Ashfield", value: "sutton-in-ashfield" },
    { label: "Swadlincote", value: "swadlincote" },
    { label: "Swaffham", value: "swaffham" },
    { label: "Swanage", value: "swanage" },
    { label: "Swanley", value: "swanley" },
    { label: "Swanscombe", value: "swanscombe" },
    { label: "Swansea", value: "swansea" },
    { label: "Swindon", value: "swindon" },
    { label: "Swiss Cottage", value: "swiss-cottage" },
    { label: "Tadcaster", value: "tadcaster" },
    { label: "Tadley", value: "tadley" },
    { label: "Tadworth", value: "tadworth" },
    { label: "Tain", value: "tain" },
    { label: "Talybont", value: "talybont" },
    { label: "Tamworth", value: "tamworth" },
    { label: "Tarbert", value: "tarbert" },
    { label: "Tarporley", value: "tarporley" },
    { label: "Taunton", value: "taunton" },
    { label: "Tavistock", value: "tavistock" },
    { label: "Taynuilt", value: "taynuilt" },
    { label: "Tayport", value: "tayport" },
    { label: "Teddington", value: "teddington" },
    { label: "Teignmouth", value: "teignmouth" },
    { label: "Telford", value: "telford" },
    { label: "Temple", value: "temple" },
    { label: "Temple Place", value: "temple-place" },
    { label: "Templecombe", value: "templecombe" },
    { label: "Tenbury Wells", value: "tenbury-wells" },
    { label: "Tenby", value: "tenby" },
    { label: "Tenterden", value: "tenterden" },
    { label: "Tetbury", value: "tetbury" },
    { label: "Tewkesbury", value: "tewkesbury" },
    { label: "Thame", value: "thame" },
    { label: "Thames Ditton", value: "thames-ditton" },
    { label: "Thatcham", value: "thatcham" },
    { label: "Thetford", value: "thetford" },
    { label: "Thirsk", value: "thirsk" },
    { label: "Thornhill", value: "thornhill" },
    { label: "Thornton Heath", value: "thornton-heath" },
    { label: "Thornton-Cleveleys", value: "thornton-cleveleys" },
    { label: "Thurso", value: "thurso" },
    { label: "Tidworth", value: "tidworth" },
    { label: "Tilbury", value: "tilbury" },
    { label: "Tillicoultry", value: "tillicoultry" },
    { label: "Tintagel", value: "tintagel" },
    { label: "Tipton", value: "tipton" },
    { label: "Tiverton", value: "tiverton" },
    { label: "Todmorden", value: "todmorden" },
    { label: "Tonbridge", value: "tonbridge" },
    { label: "Tonypandy", value: "tonypandy" },
    { label: "Tooting", value: "tooting" },
    { label: "Torpoint", value: "torpoint" },
    { label: "Torquay", value: "torquay" },
    { label: "Torrington", value: "torrington" },
    { label: "Totland Bay", value: "totland-bay" },
    { label: "Totnes", value: "totnes" },
    { label: "Tottenham", value: "tottenham" },
    { label: "Towcester", value: "towcester" },
    { label: "Tower Bridge", value: "tower-bridge" },
    { label: "Tower Hamlets", value: "tower-hamlets" },
    { label: "Tower Hill", value: "tower-hill" },
    { label: "Tower Liberty", value: "tower-liberty" },
    { label: "Trafalgar Square", value: "trafalgar-square" },
    { label: "Tredegar", value: "tredegar" },
    { label: "Tregaron", value: "tregaron" },
    { label: "Treharris", value: "treharris" },
    { label: "Treorchy", value: "treorchy" },
    { label: "Trimdon Station", value: "trimdon-station" },
    { label: "Tring", value: "tring" },
    { label: "Troon", value: "troon" },
    { label: "Trowbridge", value: "trowbridge" },
    { label: "Truro", value: "truro" },
    { label: "Tufnell Park", value: "tufnell-park" },
    { label: "Tunbridge Wells", value: "tunbridge-wells" },
    { label: "Turriff", value: "turriff" },
    { label: "Twickenham", value: "twickenham" },
    { label: "Uckfield", value: "uckfield" },
    { label: "Ulceby", value: "ulceby" },
    { label: "Ullapool", value: "ullapool" },
    { label: "Ulverston", value: "ulverston" },
    { label: "Umberleigh", value: "umberleigh" },
    { label: "Upminster", value: "upminster" },
    { label: "Upney", value: "upney" },
    { label: "Upton Park", value: "upton-park" },
    { label: "Usk", value: "usk" },
    { label: "Uttoxeter", value: "uttoxeter" },
    { label: "Uxbridge", value: "uxbridge" },
    { label: "Ventnor", value: "ventnor" },
    { label: "Verwood", value: "verwood" },
    { label: "Virginia Water", value: "virginia-water" },
    { label: "Wadebridge", value: "wadebridge" },
    { label: "Wadhurst", value: "wadhurst" },
    { label: "Wakefield", value: "wakefield" },
    { label: "Wallasey", value: "wallasey" },
    { label: "Wallingford", value: "wallingford" },
    { label: "Wallington", value: "wallington" },
    { label: "Wallsend", value: "wallsend" },
    { label: "Walsall", value: "walsall" },
    { label: "Walsingham", value: "walsingham" },
    { label: "Waltham Abbey", value: "waltham-abbey" },
    { label: "Waltham Cross", value: "waltham-cross" },
    { label: "Walton-on-Thames", value: "walton-on-thames" },
    { label: "Walton-on-the-Naze", value: "walton-on-the-naze" },
    { label: "Wanstead", value: "wanstead" },
    { label: "Wantage", value: "wantage" },
    { label: "Wapping", value: "wapping" },
    { label: "Ware", value: "ware" },
    { label: "Wareham", value: "wareham" },
    { label: "Warlingham", value: "warlingham" },
    { label: "Warminster", value: "warminster" },
    { label: "Warrington", value: "warrington" },
    { label: "Warwick", value: "warwick" },
    { label: "Washington", value: "washington" },
    { label: "Watchet", value: "watchet" },
    { label: "Waterlooville", value: "waterlooville" },
    { label: "Watford", value: "watford" },
    { label: "Watlington", value: "watlington" },
    { label: "Wedmore", value: "wedmore" },
    { label: "Wednesbury", value: "wednesbury" },
    { label: "Welling", value: "welling" },
    { label: "Wellingborough", value: "wellingborough" },
    { label: "Wellington", value: "wellington" },
    { label: "Wells", value: "wells" },
    { label: "Wells-next-the-Sea", value: "wells-next-the-sea" },
    { label: "Welshpool", value: "welshpool" },
    { label: "Welwyn", value: "welwyn" },
    { label: "Welwyn Garden City", value: "welwyn-garden-city" },
    { label: "Wembley", value: "wembley" },
    { label: "Wennington", value: "wennington" },
    { label: "West Bromwich", value: "west-bromwich" },
    { label: "West Byfleet", value: "west-byfleet" },
    { label: "West Drayton", value: "west-drayton" },
    { label: "West Ham", value: "west-ham" },
    { label: "West Kilbride", value: "west-kilbride" },
    { label: "West Malling", value: "west-malling" },
    { label: "West Molesey", value: "west-molesey" },
    { label: "West Wickham", value: "west-wickham" },
    { label: "Westbury", value: "westbury" },
    { label: "Westbury-on-Severn", value: "westbury-on-severn" },
    { label: "Westcliff-on-Sea", value: "westcliff-on-sea" },
    { label: "Westerham", value: "westerham" },
    { label: "Westgate-on-Sea", value: "westgate-on-sea" },
    { label: "Westhill", value: "westhill" },
    { label: "Weston-super-Mare", value: "weston-super-mare" },
    { label: "Wetherby", value: "wetherby" },
    { label: "Weybridge", value: "weybridge" },
    { label: "Weymouth", value: "weymouth" },
    { label: "Whitby", value: "whitby" },
    { label: "Whitchurch", value: "whitchurch" },
    { label: "Whitechapel", value: "whitechapel" },
    { label: "Whitehaven", value: "whitehaven" },
    { label: "Whitland", value: "whitland" },
    { label: "Whitley Bay", value: "whitley-bay" },
    { label: "Whitstable", value: "whitstable" },
    { label: "Whyteleafe", value: "whyteleafe" },
    { label: "Wick", value: "wick" },
    { label: "Wickford", value: "wickford" },
    { label: "Widnes", value: "widnes" },
    { label: "Wigan", value: "wigan" },
    { label: "Wigston", value: "wigston" },
    { label: "Wigton", value: "wigton" },
    { label: "Willenhall", value: "willenhall" },
    { label: "Wilmslow", value: "wilmslow" },
    { label: "Wimborne", value: "wimborne" },
    { label: "Wincanton", value: "wincanton" },
    { label: "Winchelsea", value: "winchelsea" },
    { label: "Winchester", value: "winchester" },
    { label: "Windermere", value: "windermere" },
    { label: "Windlesham", value: "windlesham" },
    { label: "Windsor", value: "windsor" },
    { label: "Wingate", value: "wingate" },
    { label: "Winkleigh", value: "winkleigh" },
    { label: "Winscombe", value: "winscombe" },
    { label: "Winsford", value: "winsford" },
    { label: "Wirral", value: "wirral" },
    { label: "Wisbech", value: "wisbech" },
    { label: "Wishaw", value: "wishaw" },
    { label: "Witham", value: "witham" },
    { label: "Withernsea", value: "withernsea" },
    { label: "Witney", value: "witney" },
    { label: "Woking", value: "woking" },
    { label: "Wokingham", value: "wokingham" },
    { label: "Wolverhampton", value: "wolverhampton" },
    { label: "Woodbridge", value: "woodbridge" },
    { label: "Woodford", value: "woodford" },
    { label: "Woodford Bridge", value: "woodford-bridge" },
    { label: "Woodford Green", value: "woodford-green" },
    { label: "Woodhall Spa", value: "woodhall-spa" },
    { label: "Woodstock", value: "woodstock" },
    { label: "Woolacombe", value: "woolacombe" },
    { label: "Wooler", value: "wooler" },
    { label: "Worcester", value: "worcester" },
    { label: "Worcester Park", value: "worcester-park" },
    { label: "Workington", value: "workington" },
    { label: "Worksop", value: "worksop" },
    { label: "Worthing", value: "worthing" },
    { label: "Wotton-under-Edge", value: "wotton-under-edge" },
    { label: "Wymondham", value: "wymondham" },
    { label: "Yarm", value: "yarm" },
    { label: "Yarmouth", value: "yarmouth" },
    { label: "Yateley", value: "yateley" },
    { label: "Yelverton", value: "yelverton" },
    { label: "Yeovil", value: "yeovil" },
    { label: "York", value: "york" },
    { label: "Ystrad Meurig", value: "ystrad-meurig" },
    { label: "Walthamstow", value: "walthamstow" },
]

export const INVENTORY= [
  { label: 'Bed (Single)', value: 'bed-(single)' },
  { label: 'Bed (Double)', value: 'bed-(double)' },
  { label: 'Chair', value: 'chair' },
  { label: 'Coffee Table', value: 'coffee-table' },
  { label: 'Cupboard', value: 'cupboard' },
  { label: 'Dining Chair', value: 'dining-chair' },
  { label: 'Dining Table', value: 'dining-table' },
  { label: 'Freezer', value: 'freezer' },
  { label: 'Fridge', value: 'fridge' },
  { label: 'Iron', value: 'iron' },
  { label: 'Microwave', value: 'microwave' },
  { label: 'Oven', value: 'oven' },
  { label: 'Sofa Set', value: 'sofa-set' },
  { label: 'Vacuum Cleaner', value: 'vacuum-cleaner' },
  { label: 'Washing Machine', value: 'washing-machine' },
  { label: 'Chair & Desk', value: 'chair-&-desk' },
  { label: 'Shower', value: 'shower' },
  { label: 'Gas Cooker', value: 'gas-cooker' },
  { label: 'Electric Cooker', value: 'electric-cooker' },
  { label: 'TV', value: 'tv' },
  { label: 'Gas Fire', value: 'gas-fire' },
  { label: 'Curtain & Net', value: 'curtain-&-net' },
  { label: 'Wooden Floor', value: 'wooden-floor' },
  { label: 'Kitchen Units & Worktop', value: 'kitchen-units-&-worktop' },
  { label: 'Bedside Table', value: 'bedside-table' },
  { label: 'Wardrobes', value: 'wardrobes' },
  { label: 'Chest Of Drawers', value: 'chest-of-drawers' },
  { label: 'Computer Table', value: 'computer-table' },
  { label: 'Computer Chair', value: 'computer-chair' },
  { label: 'Settee', value: 'settee' }
]

export const LOCATION=[
  { label: "Bedroom Five ", value: "bedroom-five" },
  { label: "Bedroom Four ", value: "bedroom-four" },
  { label: "Bedroom One ", value: "bedroom-one" },
  { label: "Bedroom Six ", value: "bedroom-six" },
  { label: "Bedroom Three ", value: "bedroom-three" },
  { label: "Bedroom Two ", value: "bedroom-two" },
  { label: "Bathroom", value: "bathroom" },
  { label: "Hall", value: "hall" },
  { label: "Studio", value: "studio" },
  { label: "Store Cupboard", value: "store-cupboard" },
  { label: "Kitchen", value: "kitchen" },
  { label: "Living Room", value: "living-room" },
  { label: "Entrance", value: "entrance" }
]


export const bankOptions = [
  { label: "Abbey", value: "abbey" },
  { label: "BACS", value: "bacs" },
  { label: "Barclays", value: "barclays" },
  { label: "Cash", value: "cash" },
  { label: "Cheque", value: "cheque" },
  { label: "Halifax", value: "halifax" },
  { label: "HSBC", value: "hsbc" },
  { label: "Lloyds", value: "lloyds" },
  { label: "NatWest", value: "natwest" },
];